# Application metadata
name: groceryapp
description: "A new Flutter project."
publish_to: 'none'  # Prevents accidental publishing to pub.dev
version: 1.0.0+1

# Dart SDK version constraint
environment:
  sdk: ^3.5.1

# Application dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # Firebase services
  firebase_core: ^3.9.0    # Firebase initialization
  cloud_firestore: ^5.6.0  # Cloud database
  firebase_storage: ^12.3.7 # File storage
  
  # State management
  provider: ^6.1.2
  
  # File and image handling
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_image_compress: ^1.1.0
  
  

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter configuration
flutter:
  uses-material-design: true
  # Uncomment and add assets/fonts as needed:
  # assets:
  #   - images/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf